"""empty message

Revision ID: 62e8a63ff85a
Revises:
Create Date: 2024-10-05 14:08:46.385770

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62e8a63ff85a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'emails',
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('mail', sa.String(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('pk'),
    )
    op.create_table(
        'events',
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('event_name', sa.String(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('pk'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('emails')
    # ### end Alembic commands ###
